[theme]
# Primary accent for interactive elements
primaryColor = '#0f345d'

# Background color for the main content area
backgroundColor = '#FFFFFF'


# Color used for almost all text
textColor = '#0f345d'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[server]
headless = true